### PR TITLE
added refresh functionality to  refresh the query history.

### PR DESCRIPTION
**Pull request by sanyamjain04**
## preview
https://user-images.githubusercontent.com/107163858/232310435-b97c188c-2a2c-4247-a874-33de75796c7e.mp4

### button preview
image

### CODE REVIEW

**Comment by paraswaykole** [comment]
Looks like the whole file changed. Can you add only the necessary code changes into the PR?

**Comment by sanyamjain04** [comment]
Actually whole file is not changed, I have prettier extension installed, so on save, it added spaces and commas. 

these are main changes I have made 
image
image

**Comment by paraswaykole** [comment]
Got it! the project does not use prettier, can you disable it for this project and make the changes?

**Comment by sanyamjain04** [comment]
Alright! No problem.

**Comment by sanyamjain04** [comment]
@paraswaykole done

**Pull request merged**
