### PR TITLE
feature: dockerized the slashbase.

### PR DESCRIPTION
**Pull request by dozheiny**
I've made the necessary changes to Dockerize the slashbase and added a supervisord.conf file for running the frontend and backend services in the background. Due to limitations with Docker, I've also added a new environment variable called 'cli' to ensure that only the web runs when set to false and both the CLI and web run together when set to true. I've also addressed the EOF issue encountered when running the Docker service. Please review and let me know if there are any further concerns.
Thanks.

### CODE REVIEW

**Comment by paraswaykole** [comment]
Is it dockerized for local development? or production dev?

**Comment by dozheiny** [comment]
> Is it dockerized for local development? or production deployment?

For both. But I suggest to use in local deployment.

**Comment by paraswaykole** [comment]
supervisord.conf is not present in the PR?

**Comment by dozheiny** [comment]
Sorry, I forgot to add it into git.
My bad.

**Comment by dozheiny** [comment]
I added it.

**Comment by paraswaykole** [comment]
Sorry! won't be able accept this as the app recently changed to being a desktop app using wails framework. 
I hope you like the new direction of Slashbase IDE.

Thanks for the PR anyway 🙌!

Closing this!

**Pull request closed without merging**
